### ISSUE TITLE
Missing test data files

### ISSUE THREAD

**Issue by ikd-sci** [kuadrat/data_slicer#1]
Attempting to execute
python3 -m data_slicer.tests.test
or python3 -m data_slicer.tests.cool_test

> FileNotFoundError: [Errno 2] No such file or directory: 'data_slicer-master/data_slicer/data/testdata_100_150_200.p'

**Comment by kuadrat** [comment]
Thanks for submitting this issue.
Tests have been updated and should work according to https://data-slicer.readthedocs.io/en/latest/examples.html
